---
abstract: 'wrap open/sysopen and give them a nice and simple interface'
author:
  - 'Lukas Mai <l.mai@web.de>'
build_requires:
  File::Spec: 0
  File::Temp: 0
  IO::Handle: 0
  Test::Fatal: 0
  Test::More: 0
  open: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-Open
requires:
  Carp: 0
  Errno: 0
  Exporter: 0
  Fcntl: 0
  File::Basename: 0
  strict: 0
  warnings: 0
resources:
  repository: git://github.com/mauke/File-Open.git
version: 0.040
