---
abstract: 'wrap open/sysopen and give them a nice and simple interface'
author:
  - 'Lukas Mai <l.mai@web.de>'
build_requires:
  File::Spec: 0
  File::Temp: 0.19
  IO::Handle: 0
  Test::Fatal: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.56
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-Open
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  Errno: 0
  Exporter: 0
  Fcntl: 0
  File::Basename: 0
  strict: 0
  warnings: 0
resources: {}
version: 0.100
